version: "3.9"
services:
  gateway: 
    image: garage-gateway:latest
    container_name: garage-gateway
    build: ./gateway
    ports:
    - target: 80
      published: 80
  backend:
    container_name: garage-backend
    build: ./backend
    image: garage-backend:latest
    environment:
      MYSQL_SERVER:
      MYSQL_USER:
      MYSQL_PASSWORD:    
  frontend:
    container_name: garage-frontend
    build: ./frontend
    image: garage-frontend:latest
      


